SSN Validation Attribute
johnkallstrom/GarageThree pull request #11
Opened 2024-05-03 09:32 UTC by johnkallstrom

- Add validation attribute for SSN

2024-05-03 11:10 UTC, suny-am requested changes
Looks good! Would be good to silence those warnings though!

2024-05-03 11:20 UTC, Ezeih approved these changes

2024-05-03 11:38 UTC, johnkallstrom commented
> Looks good! Would be good to silence those warnings though!

Resolved

2024-05-03 14:02 UTC, suny-am approved these changes
🎖️

2024-05-06 06:25 UTC, Ca2le approved these changes

2024-05-06 06:25 UTC, merged