Vehicle Index View + Action
johnkallstrom/GarageThree pull request #14
Opened 2024-05-03 13:27 UTC by johnkallstrom

- [x] Add vehicle index view
- [x] Add vehicle index action
- [x] Add vehicle index view model
- [x] Add new mappings for vehicle type
- [x] Display vehicle garage and type
- [x] Add new Filter method to IRepository
- [x] Add garage dropdown to vehicle index
- [x] Filter vehicles based on their garage

Extended our repository interface with a new method called Filter() which takes a QueryParams object as a parameter. 
We could add more properties that we want to filter on in QueryParams, just have to make sure that they are somewhat generic and can be useful for all entities. At the moment I just added SearchTerm, string and Id, object?

2024-05-03 14:01 UTC, suny-am requested changes

2024-05-03 14:01 UTC, suny-am commented on GarageThree.Web/Views/Vehicles/Index.cshtml
> +                    <button type="button" class="btn btn-secondary" asp-controller="Vehicle" asp-action="Details" asp-route-id="@vehicle.Id">Details</button>
Just need to wrap the buttons in anchor element to get the actions to trigger.

2024-05-06 06:26 UTC, Ca2le approved these changes

2024-05-06 11:09 UTC, Ezeih approved these changes

2024-05-06 11:27 UTC, suny-am approved these changes

2024-05-06 11:28 UTC, merged