Fix navbar button links; Fix Index View Button texts
johnkallstrom/GarageThree pull request #17
Opened 2024-05-06 13:17 UTC by suny-am

Fix for some mistakes made in the hrefs of the navbar buttons as well as the text contents of the buttons in the Member Index View

2024-05-06 14:02 UTC, Ezeih approved these changes

2024-05-07 06:16 UTC, Ca2le approved these changes

2024-05-07 13:12 UTC, johnkallstrom requested changes
Bra fix! Men de går också att lägga bootstrap button klasser direkt på anchors för att få dem se ut som knappar. På så vis behöver man inte wrappa en button med en anchor. Liten detalj kanske men men :) 

`<a class="btn btn-secondary">Button Text</a>`
Istället för tex
`<a><button class="btn btn-danger">Delete</button></a>`

2024-05-07 13:15 UTC, johnkallstrom approved these changes

2024-05-07 14:29 UTC, merged